### ISSUE TITLE
Wishes, errors?? and strangeness

### ISSUE THREAD

**Issue by tthkbw** [godbout/kindaVim.theapp#25] opened 2021-12-25 17:58 UTC
In the I wish this worked category:

More support for yank and put. For example, xp doesn't work to fix transposition errors. You can't yank in visual mode, etc. I know these are documented, but when editing a file, copy and paste and delete of selections is common and quite useful.

In the probably wrong category:

In text fields, when you enter Normal Mode you get a block cursor that highlights a character. When you leave Normal Mode, this block cursor is still present, but now it means selection to the application. So, if you leave Normal Mode and immediately start typing, the character you were on in Normal mode is replaced. the result of this is that leaving normal mode requires additional keystrokes. I now have to do something (click the mouse, move with an arrow key) to get ride of the highlight. Not what I want and probably not what most folks want.
 
The following are some cosmetic issues--feedback about weird shit that doesn't behave as expected. 

I see strange cursor behavior in some situations when entering Normal Mode. 

For example, if I mouse click a menu item in Safari Technology Preview, then enter Normal Mode, the highlighted menu item moves one position to the left. Following that, Normal mode behaves as expected with cursor movement keys.

In Numbers, if I am in a spreadsheet cell (just the cell is highlighted, I did not place the cursor within the text of the cell), when I enter Normal Mode, again the cursor jumps one position to the left. If I double-click the cell to edit the cell's contents, then enter Normal Mode, again the cursor jumps one position to the left.

In Notes, when in the menu, cursor movement has no effect, the keystrokes are ignored. 

Photos behaves like Safari. NetNewsWire works as expected. Calendar works as expected. 

In Messages, the menu jumps left. 

In Drafts, the menu doesn't work. 

Don't you love this shit?

**Comment by godbout** [comment] 2021-12-25 18:09
dude i'm trying to sleep.

**Comment by godbout** [comment] 2021-12-25 18:42
> More support for yank and put.

i have to admit that currently it's pretty basic. mainly coz i personally use it only to insult people on Twitter. so the question for which i already dread the answer: do you expect registers? 🥺️

> For example, xp doesn't work to fix transposition errors. 

interesting. didn't know about this trick. but yeah that makes as currently design kV doesn't fill the clipboard with whatever you delete. i don't think it made sense to do that with a single clipboard, but at the same i was too lazy to build the registers. am i answering my question from above? ☹️

> You can't yank in visual mode, etc. 

dude wtf. i am appalled. Visual Mode `y` should work. or am i missing something? (could be. i only started using Vim a week ago LMAO.)

> I know these are documented, but when editing a file, copy and paste and delete of selections is common and quite useful.

makes sense. i guess i'm not that of a kV Pro Max user myself, but i get you. i was waiting for kV to pick up some traction first because i don't use yanking and deleting like that but yeah know i feel the pressure. 

> In the probably wrong category:
> 
> In text fields, when you enter Normal Mode you get a block cursor that highlights a character. When you leave Normal Mode, this block cursor is still present, but now it means selection to the application. So, if you leave Normal Mode and immediately start typing, the character you were on in Normal mode is replaced. the result of this is that leaving normal mode requires additional keystrokes. I now have to do something (click the mouse, move with an arrow key) to get ride of the highlight. Not what I want and probably not what most folks want.

wait i know that one. how do you leave Normal Mode? if you leave it properly (haha) with `i`, `a`, etc..., the block cursor should be handled properly. if you leave with the way you entered Normal Mode (`esc` or Custom Keyboard Shortcut) it will leave the selection. currently this is by design, so that you can comment, indent or run your selection through macOS services (or Alfred Universal Actions etc etc). (not documented though, more like a Christmas egg.)

> The following are some cosmetic issues--feedback about weird shit that doesn't behave as expected.

😂️😂️😂️ i fucking love it

> I see strange cursor behavior in some situations when entering Normal Mode.
> 
> For example, if I mouse click a menu item in Safari Technology Preview, then enter Normal Mode, the highlighted menu item moves one position to the left. Following that, Normal mode behaves as expected with cursor movement keys.
> 
> In Numbers, if I am in a spreadsheet cell (just the cell is highlighted, I did not place the cursor within the text of the cell), when I enter Normal Mode, again the cursor jumps one position to the left. If I double-click the cell to edit the cell's contents, then enter Normal Mode, again the cursor jumps one position to the left.
> 

yeah that's because kV can't read the text (can't believe some of Apple's own apps don't support Apple's own Accessibility shit) so it falls back to the Keyboard Strategy, and KS does a `leftArrow` key when entering Normal Mode. that happens only if the input is detected as `Text Element`, which seems to be the cases you're seeing. i'll have a look but i'm afraid this is gonna be an all or nothing thing. like it fails sometimes, or i remove the jump to the left in any case. which means if you enter Normal Mode in a `Text Element` where kV can't read the text (like Mail), you will not have this little cute jump to the left in the text.

> In Notes, when in the menu, cursor movement has no effect, the keystrokes are ignored.

what menu? macOS menu? who uses Notes anyways 🙄️

> Photos behaves like Safari. NetNewsWire works as expected. Calendar works as expected.

i'm afraid on the UI stuff kV might fail your expectations. it's just key remapping. so you can't access things you wouldn't access with other keys. for that you'd need to use something like Vimac. 

> In Messages, the menu jumps left.
> 
> In Drafts, the menu doesn't work.

sorry again, not sure what "menu" you're talking about.

> Don't you love this shit?

at first i thought yes but thinking more deeply about it i think yes.

**Comment by godbout** [comment] 2021-12-25 18:46
are you still willing to pay me every month though? if yes please kindly disregard my answers above.

**Comment by godbout** [comment] 2021-12-25 18:48
> if I am in a spreadsheet cell

also cool people don't use spreadsheets. just saying.

(and you missed the opportunity of a lifetime: spreadshit.)

**Comment by tthkbw** [comment] 2021-12-26 17:00
Well . . .

1. "Dude, I'm trying to sleep" -- Sorry about that, particularly on Christmas!

2. "more support for Yank and Put" -- While registers are a great feature in Vim, I don't think you need anything more than the system clipboard in kindaVim. For my use, I don't care about the system clipboard being overwritten while using kindaVim--I actually expect it. Yank and Put should just use it. Almost all uses of Vim expect that deletions done by commands like 'x' 'X' 'dd' 'c' etc. will be available to Put with commands like 'p' and 'P'. To make that simple, I think you just use the system clipboard. However, Vim itself uses its own internal buffers for this purpose by default. I have installed your most recent version, and see that visual mode yank and put work now--thanks!--and that you use the system clipboard. Think about saving any deleted text to the clipboard for Put as well.
3. I have learned to leave Normal Mode properly! I must have had a dumb shit attack. I knew I had seen this work the way I expected, but couldn't figure out how I did it. I just need practice to make this a habit. From too long using Karabiner (where I used caps lock as a hyper key for functions like kindaVim) I was in the habit of entering and leaving the mode by tapping capslock. 
4. With respect to my cosmetic issues, these are not particularly important to me. I will rarely use kindaVim in application menus, or for scrolling in mail or safari, for example. kindaVim's importance to me is being able to use Vim to edit text pretty much anywhere I need to on my Mac. It's all about efficiency. When I am editing, I don't want to have to use my mouse (and leave the keyboard), nor do I want to use the contortionist multiple command/control/option key combinations to get simple things done (that makes me feel like I'm using Emacs). That's the beauty of Vim--Normal Mode and being able to edit with fingers on the home row by typing simple characters. 
5. When I referred to Menus, I meant the application menus, like File, Edit, View, etc that appear at the top of the screen. 
6. Paying--Ha! I would be happy to purchase kindaVim, but as with all purchases, price matters! I much prefer non-subscription purchases with regular updates being paid. Or at least, if a subscription, when I quit paying it still works, I just don't get upgrades. Having said that, I am aware that I pay regularly for many apps that are upgraded yearly or so. But it feels different to commit to a subscription. What's a fair price? Good question. For me, $15 would be a no-brainer. $30 would take some thought. $50 is probably too much. Same for subscriptions, just think annual cost.
7. "cool people don't use spreadsheets" I never said I was cool! But I can cuss with the best of them.
 have been a vi/stevie/elvis/vim user since the early 80s--so, yes, in addition to not being cool, I am old. I even wrote an x86 assembly language version of vi for use on my PC in 1989. For the time, it was fast!

**Comment by godbout** [comment] 2021-12-26 18:49
> 1. "Dude, I'm trying to sleep" -- Sorry about that, particularly on Christmas!

it's gonna be Christmas already??? 😮️☹️

> 2. While registers are a great feature in Vim, I don't think you need anything more than the system clipboard in kindaVim.

yeah too much work anyways. not in v1, before the sub starts.

> Almost all uses of Vim expect that deletions done by commands like 'x' 'X' 'dd' 'c' etc. will be available to Put with commands like 'p' and 'P'.

`dl`, `x`, `dh`, `X`, `d`, `c` done already in be'a15 (should be out in two or three days). `dd` should be in too. and when i mean done i mean Accessibility Strategy, Keyboard Strategy, Text Elements, Non Text Elements, etc, etc. just preparing for the sub talk 😂️

> To make that simple, I think you just use the system clipboard. However, Vim itself uses its own internal buffers for this purpose by default. I have installed your most recent version, and see that visual mode yank and put work now--thanks!--and that you use the system clipboard. 

as said above, the Visual Mode `y` was already done (like 3 months ago: https://github.com/godbout/AccessibilityStrategyTestApp/tree/master/AccessibilityStrategyTestAppTests/AccessibilityStrategy/VisualMode/Moves/Linewise both Characterwise and Linewise). i used them all the time. is it possible that maybe you were using it in browsers and was trying to paste several times? browsers are restricted and it's a MEGAPITA. when you yank you can only paste once (currently). 

> 3. I have learned to leave Normal Mode properly! I must have had a dumb shit attack. I knew I had seen this work the way I expected, but couldn't figure out how I did it. I just need practice to make this a habit. From too long using Karabiner (where I used caps lock as a hyper key for functions like kindaVim) I was in the habit of entering and leaving the mode by tapping capslock.

but to be fair to you the `esc` to quit (or using your own Keyboard Shortcut) is really not consistent with Vim. it's for me to comment and indent multiple lines easily while i'm using kV to build kV 🤯️ i should probably mention this somewhere but now sure yet how and where so probably it will never happen.

> 4. With respect to my cosmetic issues, these are not particularly important to me. I will rarely use kindaVim in application menus, or for scrolling in mail or safari, for example. kindaVim's importance to me is being able to use Vim to edit text pretty much anywhere I need to on my Mac. It's all about efficiency. When I am editing, I don't want to have to use my mouse (and leave the keyboard), nor do I want to use the contortionist multiple command/control/option key combinations to get simple things done (that makes me feel like I'm using Emacs). That's the beauty of Vim--Normal Mode and being able to edit with fingers on the home row by typing simple characters.

ok. i personally like to go up down in stuff like Dash, or Safari when i'm reading etc.

> 5. When I referred to Menus, I meant the application menus, like File, Edit, View, etc that appear at the top of the screen.

got it. i saw that Notes is stealing/keeping the caret yeah. Xcode is doing that too since maybe a month. maybe some Catalyst shit. don't know. not sure. low on the list.

> 6. Paying--Ha! I would be happy to purchase kindaVim, but as with all purchases, price matters! I much prefer non-subscription purchases with regular updates being paid. Or at least, if a subscription, when I quit paying it still works, I just don't get upgrades. Having said that, I am aware that I pay regularly for many apps that are upgraded yearly or so. But it feels different to commit to a subscription. What's a fair price? Good question. For me, $15 would be a no-brainer. $30 would take some thought. $50 is probably too much. Same for subscriptions, just think annual cost.

i hate complicated, both as a user and as a craftsman. there's some nice apps out there like TablePlus that do what you're talking about. 69US. infinite license. but only updates for a year (took me a while to understand at first). plus only for one computer. plus blah blah blah. a fucking headache. also as the builder of kV and as me being me, i have no interest in spending energy and time on building different options, marketing, playing with upgrades and prices and business plans and blah blah. all i care about is creating a great product that makes me smile and laugh and that's useful to me and others while having fun. so the pricing is gonna be super straight and simple: 3US a month. that's one coffee. my view is that if someone is not sure whether my app is worth 3US a month to them, then it's definitely not for them. i opened my company in 2015. i've been charging between 100 and 1.5k an hour depending on the circumstances. this is 3 fucking US 😂️ my point being that 3US in terms of energy and time should be nothing to someone, really. at least to someone with a computer who's into Vim. 3US is probably like working 5 minutes. anyways, everyone value their time and energy differently, i get that too. 
and don't get me wrong, i'm not complaining, i enjoy every second of building kV. what i don't enjoy is the half a day a week i'm spending sucking ducks (haha autocorrect) to pay the bills. and kV is still A LOT of work. i mean you're dealing with Vim which means Normal Mode, Visual Mode, Characterwise, Linewise, Yanking Style, Inclusive Move, Exclusive Move. plus with kV you don't even own your own fucking buffer so you sometimes get good data, sometimes bad, sometimes buggy, sometimes restricted. plus there's text, and UI Elements, plus... so. a one time purchase would make absolutely no sense. i'd even have to finish the app which will never happen. i'd rather open source it and building it only for myself then.

anyways. just thoughts sharing. i like to talk/write, and it helps me clean my own ideas and see things more clearly. ultimately, there's gonna be no debate 😂️ sub of 3US a month. there's gonna be a "free" version, like with less features, that you can use forever except after you die. that'll be in the clause. in reality the 3US sub is gonna turn more into a "support the project" or "pay to get what you want faster" 😂️

> 7. "cool people don't use spreadsheets" I never said I was cool! But I can cuss with the best of them.
>    have been a vi/stevie/elvis/vim user since the early 80s--so, yes, in addition to not being cool, I am old. I even wrote an x86 assembly language version of vi for use on my PC in 1989. For the time, it was fast!

😄️ nice. not using it anymore? why not building one on Mac?!

**Comment by godbout** [comment] 2021-12-26 19:25
but tbh you being a hardcore Vim user and having built a Vi and not being hot for a small fee a month is kinda worrisome for my future life 😂️😂️😂️

**Comment by tthkbw** [comment] 2021-12-27 16:10
It is likely that my problem with visual mode y was probably due to being in a browser text field. I see that it works properly elsewhere.

With respect to $$--I would pay $3 per month, particularly with the completeness of kindaVim. As I use it more and become more dependent, I also find myself thinking I am really in Vim and putting ':w' in my text, as well as '/I want to find something'. I hope you will implement these so my text is cleaner.

I don't use my old x86 assembler version of vi because macVim is lots better 😄. Even iVim, on my iPad is better. And, I no longer have a PC in my house--switched exclusively to Macs nearly ten years ago.

**Comment by godbout** [comment] 2021-12-27 17:09
> particularly with the completeness of kindaVim.

what does that mean to you "completeness"?

> As I use it more and become more dependent, I also find myself thinking I am really in Vim and putting ':w' in my text, as well as '/I want to find something'. I hope you will implement these so my text is cleaner.

`:w`, `:q` should be coming in b16. need to figure out how to detect input field change properly. after that it's in my hands. just key remapping. although need to spend some time on integrating that new "Mode" properly in the kV Engine.

> I don't use my old x86 assembler version of vi because macVim is lots better 😄. Even iVim, on my iPad is better. And, I no longer have a PC in my house--switched exclusively to Macs nearly ten years ago.

but are those as good as kV though? 😎️

**Comment by godbout** [comment] 2021-12-30 14:12
> It is likely that my problem with visual mode y was probably due to being in a browser text field. I see that it works properly elsewhere.

i'm checking up on this. PGR Mode is tough because you can do half with the Accessibility and pinpoint and select text, but you can't delete or paste new text, so you have to go through sending keys to macOS. while cleaning the clipboard in sync. it's pretty messy. but i'd like to get this solved. would bring the current Accessibility implementation to browsers, which would be nice to select the next pron video.

**Comment by godbout** [comment] 2022-01-06 06:12
copying the deleted text to the clipboard was such a great move, thanks. not sure how i discarded this in the first place. it's day and night.

**Comment by tthkbw** [comment] 2022-01-06 15:02
You have made great progress with kindaVim. The cut and paste support for deletions is great. So is '~'! 

kindaVim is more complete than anything like this I have used before. It's also fast and reliable. 

I have been deep into finishing up a project, so have been spending most of my time in 'real' vim writing code rather than my other interests which involve writing in standard Mac apps where I will use kindaVim extensively and I can give better feedback.

**Comment by godbout** [comment] 2022-01-07 06:59
no worries.

**Comment by godbout** [comment] 2022-01-07 07:01
> kindaVim is more complete than anything like this I have used before. It's also fast and reliable.

heavy refactoring week. the *copy deletion* showed me i misunderstood some of Vim's logic. "luckily" i have a ~5k+ test suite. saved my ass a couple of times.

**Comment by godbout** [comment] 2022-02-07 12:46
anything from this thread that is still an issue? may close and/or open new issues instead. thanks.

**Comment by tthkbw** [comment] 2022-02-07 16:31
I think you have effectively covered my issues. Thanks for all the work!

**Comment by godbout** [comment] 2022-02-07 19:20
fantastic. gonna close this one. please open new issues if you have some more ideas coz they're golden ⭐️

**Closed by godbout** 2022-02-07 19:20 UTC
